[project]
name = "le-dan-comp388-assignment-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.3.0",
    "matplotlib>=3.10.6",
    "pytest>=8.4.2",
    "pytest-check>=2.5.4",
    "ruff>=0.13.1",
]
